FROM rust:1-bookworm@sha256:19817ead3289c8c631c73df281e18b59b172f6a31f4f563290f69cddd06c30e9 AS builder

WORKDIR /workspace
COPY . .
RUN rm -f rust-toolchain.toml \
    && cargo build --release --locked -p hsp-s3

FROM debian:bookworm-slim@sha256:96e378d7e6531ac9a15ad505478fcc2e69f371b10f5cdf87857c4b8188404716

COPY --from=builder /workspace/target/release/hsp-s3 /usr/local/bin/hsp-s3

USER 10001:10001
EXPOSE 8081
ENTRYPOINT ["/usr/local/bin/hsp-s3"]
