apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hsp-public-profile
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: ["hspd", "hsp-gw"]
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443

